Add search server scripts

diff --git a/bin/search b/bin/search
--- a/bin/search
+++ b/bin/search
@@ -1,1 +1,60 @@
 #!/bin/bash
+
+# set -Eeuo pipefail # seems not available if to run ./bin/index status &> /dev/null
+# set -x
+
+usage() {
+    echo "Usage: $0 (start|stop|status|restart)"
+}
+if [ $# -ne 1 ]; then
+    usage
+    exit 1
+fi
+
+case $1 in
+"start")
+    if [ ! -f var/search.sqlite3 ]; then
+        echo "Error: can't find search database var/search.sqlite3"
+        echo "Try: ./bin/searchdb create"
+        exit 1
+    fi
+    if [[ $(pgrep -f "flask --app search run --host 0.0.0.0 --port 8000") ]]; then
+        echo "Error: search server is already running"
+        exit 1
+    fi
+    ./bin/index status &> /dev/null
+    if [[ $? -ne 0 ]]; then
+        echo "Error: index server is not running"
+        echo "Try ./bin/index start"
+        exit 1
+    fi
+    echo "starting search server ..."
+    mkdir -p var/log
+    rm -f var/log/search.log
+    flask --app search run --host 0.0.0.0 --port 8000 &> var/log/search.log &
+    ;;
+
+"stop")
+    echo "stopping search server ..."
+    pkill -f 'flask --app search run --host 0.0.0.0 --port 8000' || true
+    ;;
+
+"status")
+    if [[ $(pgrep -f "flask --app search run --host 0.0.0.0 --port 8000") ]]; then
+        echo "search server running"
+        exit
+    else
+        echo "search server stopped"
+        exit 1
+    fi
+    ;;
+
+"restart")
+    ./bin/search stop
+    ./bin/search start
+    ;;
+*)
+    usage
+    exit 1
+    ;;
+esac
